final Map<String, String> enUs = {
  "Register new company info": "Register new company info",
  "Company name": "Company name",
  "Representative": "Representative",
  "Business number": "Business number",
  "Phone": "Phone",
  "Contact name": "Contact name",
  "Contact email": "Contact email",
  "Contact phone": "Contact phone",
  "Address": "Address",
  "Approval request": "Approval request",
  "Approval requested. It may take up to 2 business days.\nYou will be notified by email upon approval.":
      "Approval requested. It may take up to 2 business days.\nYou will be notified by email upon approval.",
  "Cancel": "Cancel",
  "Input text": "Input text",
  "This field is required.": "This field is required.",
  "Select company": "Select company",
  "Search": "Search",
  "Type": "Type",
  "Name": "Name",
  "Approval": "Approval",
  "Corporate": "Corporate",
  "Active": "Active",
  "Inactive": "Inactive",
  "Selection complete": "Selection complete",
  "Select content": "Select content",
  "All": "All",
  "My": "My",
  "Content title": "Content title",
  "Master": "Master",
  "Category": "Category",
  "Title": "Title",
  "Session number": "Session number",
  "Session start": "Session start",
  "Session complete": "Session complete",
  "Exists": "Exists",
  "None status": "None status",
  "Expert feedback": "Expert feedback",
  "Write": "Write",
  "Register": "Register",
  "Save": "Save",
  "Notification": "Notification",
  "Confirm": "Confirm",
  "Page not found": "Page not found",
  "Activity record detail": "Activity record detail",
  "Activity record management": "Activity record management",
  "Member info": "Member info",
  "Details": "Details",
  "Email address": "Email address",
  "Nickname": "Nickname",
  "Signup date": "Signup date",
  "Purpose": "Purpose",
  "Period": "Period",
  "Introduction": "Introduction",
  "Record info": "Record info",
  "Chatbot record": "Chatbot record",
  "Feedback status": "Feedback status",
  "Service preparing": "Service preparing",
  "New registration": "New registration",
  "Sub admin management": "Sub admin management",
  "Edit": "Edit",
  "Delete": "Delete",
  "Admin basic info": "Admin basic info",
  "Manager": "Manager",
  "Edit admin account": "Edit admin account",
  "Password": "Password",
  "Password Confirm": "Password Confirm",
  "Password Edit Confirm": "Password Edit Confirm",
  "Register new admin": "Register new admin",
  "Master login": "Master login",
  "Login": "Login",
  "Master signup": "Master signup",
  "If you have issues logging in,\ncontact mindsight@nodame.com.":
      "If you have issues logging in,\ncontact mindsight@nodame.com.",
  "Saved successfully": "Saved successfully",
  "Save failed": "Save failed",
  "Login Failed": "Login Failed",
  "Login failed.": "Login failed.",
  "Sign up": "Sign up",
  "Sign in": "Sign in",
  "Login with Google": "Login with Google",
  "Sign up with Google": "Sign up with Google",
  "Sign up with email address": "Sign up with email address",
  "or": "or",
  "Don’t have an account yet?": "Don’t have an account yet?",
  "Already have an account?": "Already have an account?",
  "Forgot password?": "Forgot password?",
  "Change Password": "Change Password",
  "Continue": "Continue",
  "Code sent successfully.": "Code sent successfully.",
  "Enter a new password.": "Enter a new password.",
  "The password does not match.": "The password does not match.",
  "No media file selected.": "No media file selected.",
  "No thumbnail file selected.": "No thumbnail file selected.",
  "error file extension": "error file extension",
  "unsupported file type": "unsupported file type",
  "Select master": "Select master",
  "Master name": "Master name",
  "Media playback": "Media playback",
  "Unable to play media.": "Unable to play media.",
  "Invalid image URL": "Invalid image URL",
  "View image": "View image",
  "Failed to load image": "Failed to load image",
  "Close": "Close",
  "Verification complete": "Verification complete",
  "Crop and Rotate": "Crop and Rotate",
  "Attached File": "Attached File",
  "Question": "Question",
  "Answer": "Answer",
  "FAQ detail": "FAQ detail",
  "FAQ list": "FAQ list",
  "FAQ Board list": "FAQ Board list",
  "FAQ Board detail": "FAQ Board detail",
  "FAQ Board Edit": "FAQ Board Edit",
  "FAQ New registration": "FAQ New registration",
  "Notice list": "Notice list",
  "Notice detail": "Notice detail",
  "Notice Board list": "Notice Board list",
  "Notice Board detail": "Notice Board detail",
  "Notice Board Edit": "Notice Board Edit",
  "Notice New registration": "Notice New registration",
  "Free Board list": "Free Board list",
  "Free Board detail": "Free Board detail",
  "Free Board Edit": "Free Board Edit",
  "Free Board New registration": "Free Board New registration",
  "Body": "Body",
  "Comment List": "Comment List",
  "Write a Comment": "Write a Comment",
  "Inquiry board list": "Inquiry board list",
  "Inquiry board detail": "Inquiry board detail",
  "Inquiry board Edit": "Inquiry board Edit",
  "Inquiry board New registration": "Inquiry board New registration",
  "Response": "Response",
  "Pending": "Pending",
  "not hovering": "not hovering",
  "Login info": "Login info",
  "ID": "ID",
  "Department": "Department",
  "Permission": "Permission",
  "Contact number": "Contact number",
  "Recent activity": "Recent activity",
  "role": "Role",
  "Operation": "Operation",
  "Product management": "Product management",
  "Development": "Development",
  "Select Option": "Select Option",
  "Change password": "Change password",
  "Current password": "Current password",
  "New password": "New password",
  "Please enter some text": "Please enter some text",
  "Created by master": "Created by master",
  "Exposure Status": "Exposure Status",
  "Day session": "Day session",
  "Thumbnail file": "Thumbnail file",
  "Content": "Content",
  "Participating members": "Participating members",
  "Completed members": "Completed members",
  "Likes": "Likes",
  "Exposure": "Exposure",
  "Note": "Note",
  "Change exposure": "Change exposure",
  "Views": "Views",
  "Download Excel template": "Download Excel template",
  "Media File": "Media File",
  "Target Language": "Target Language",
  "Content New Registration": "Content New Registration",
  "Content Edit": "Content Edit",
  "Basic info": "Basic info",
  "Register content": "Register content",
  "Google Analytics": "Google Analytics",
  "Daily plan Complete rate": "Daily plan Complete rate",
  "All View": "All View",
  "Complete rate": "Complete rate",
  "Members accessed yesterday": "Members accessed yesterday",
  "Number of events in the last 7 days": "Number of events in the last 7 days",
  "Returning members in the last 7 days":
      "Returning members in the last 7 days",
  "Registered users": "Registered users",
  "Not registered": "Not registered",
  "Active members": "Active members",
  "Inactive members": "Inactive members",
  "not registered": "Not registered",
  "inactive": "Inactive",
  "Sign-up compelete": "Sign-up complete",
  "Affiliation": "Affiliation",
  "Conversion date": "Conversion date",
  "Member info Edit": "Edit member info",
  "Sign-up complete": "Sign-up complete",
  "Logout": "Logout",
  "Cannot download image": "Cannot download image",
  "Error downloading image": "Error downloading image",
  "Failed to load video.": "Failed to load video.",
  "No aggregated data.": "No aggregated data.",
  "Change": "Change",
  "Breath": "Breath",
  "Theory": "Theory",
  "Mindful Art": "Mindful Art",
  "ASMR": "ASMR",
  "Art & Music": "Art & Music",
  "Beginner": "Beginner",
  "Intermediate": "Intermediate",
  "Advanced": "Advanced",
  "Satisfied": "Satisfied",
  "Relaxed": "Relaxed",
  "Calm": "Calm",
  "Sleepy": "Sleepy",
  "Tired": "Tired",
  "Bored": "Bored",
  "Depressed": "Depressed",
  "Sad": "Sad",
  "Miserable": "Miserable",
  "Upset": "Upset",
  "Stressed": "Stressed",
  "Scared": "Scared",
  "Annoyed": "Annoyed",
  "Nervous": "Nervous",
  "Angry": "Angry",
  "Alarmed": "Alarmed",
  "Surprised": "Surprised",
  "Excited": "Excited",
  "Delighted": "Delighted",
  "Happy": "Happy",
  "Just rest": "Just rest",
  "Sleep": "Sleep",
  "Workspace": "Workspace",
  "Movement": "Movement",
  "Male": "Male",
  "Female": "Female",
  "Nonbinary": "Nonbinary",
  "Non Exposure": "Non Exposure",
  "You can upload video or audio files.":
      "You can upload video or audio files.",
  "The media file is currently being transcoded and cannot be modified.":
      "The media file is currently being transcoded and cannot be modified.",
  "After entering tags, register by clicking '+' or pressing Enter.":
      "After entering tags, register by clicking '+' or pressing Enter.",
  "Please enter an introduction within 150 characters.":
      "Please enter an introduction within 150 characters.",
  "Content list": "Content list",
  "Level": "Level",
  "Situation": "Situation",
  "Emotion": "Emotion",
  "Input Text": "Input Text",
  "click to upload .mp4 .mp3 .wav": "click to upload .mp4 .mp3 .wav",
  "click to upload .jpg .jpeg .png": "click to upload .jpg .jpeg .png",
  "Content details": "Content details",
  "Join Date": "Join Date",
  "First name": "First name",
  "Last name": "Last name",
  "Gender": "Gender",
  "Year of birth": "Year of birth",
  "Date": "Date",
  "Author": "Author",
  "Answered": "Answered",
  "Comments": "Comments",
  "All Notifications": "All Notifications",
  "I receive all notifications.": "I receive all notifications.",
  "Select Notification Type": "Select Notification Type",
  "Email": "Email",
  "SMS": "SMS",
  "Select Notification Items": "Select Notification Items",
  "Notice": "Notice",
  "Inquiries and Answers": "Inquiries and Answers",
  "Content Approval and Modification": "Content Approval and Modification",
  "Settlement": "Settlement",
  "Please enter your display name": "Please enter your display name",
  "Inquiry board": "Inquiry board",
  "Help": "Help",
  "Streaming Settlement": "Streaming Settlement",
  "Please enter the title within 100 characters.":
      "Please enter the title within 100 characters.",
  "It will be displayed in the specified language version.":
      "It will be displayed in the specified language version.",
  "It must be set to “exposed” in order to be shown in the service.":
      "It must be set to “exposed” in order to be shown in the service.",
};
