final Map<String, String> koKR = {
  "Register new company info": "회사 정보 신규 등록",
  "Company name": "회사명",
  "Representative": "대표자",
  "Business number": "사업자 번호",
  "Phone": "전화번호",
  "Contact name": "담당자명",
  "Contact email": "담당자 이메일",
  "Contact phone": "담당자 전화번호",
  "Address": "주소",
  "Approval request": "승인 요청",
  "Approval requested. It may take up to 2 business days.\nYou will be notified by email upon approval.":
      "승인 요청되었습니다. 최대 2영업일이 소요될 수 있습니다.\n승인 완료 시 이메일로 알려드리겠습니다.",
  "Cancel": "취소",
  "Input text": "텍스트 입력",
  "This field is required.": "필수 입력 항목입니다.",
  "Select company": "회사 선택",
  "Search": "검색",
  "Type": "유형",
  "Name": "이름",
  "Approval": "승인",
  "Corporate": "법인",
  "Active": "활성",
  "Inactive": "비활성",
  "Selection complete": "선택 완료",
  "Select content": "콘텐츠 선택",
  "All": "전체",
  "My": "내 콘텐츠",
  "Content title": "콘텐츠 제목",
  "Master": "마스터",
  "Category": "카테고리",
  "Title": "제목",
  "Session number": "세션 수",
  "Session start": "세션 시작",
  "Session complete": "세션 완료",
  "Exists": "존재함",
  "None status": "상태 없음",
  "Expert feedback": "전문가 피드백",
  "Write": "작성",
  "Register": "등록",
  "Save": "저장",
  "Notification": "알림",
  "Confirm": "확인",
  "Page not found": "페이지를 찾을 수 없습니다",
  "Activity record detail": "활동 기록 상세",
  "Activity record management": "활동 기록 관리",
  "Member info": "회원 정보",
  "Details": "상세",
  "Email address": "이메일 주소",
  "Nickname": "닉네임",
  "Signup date": "가입일",
  "Purpose": "목적",
  "Period": "기간",
  "Introduction": "소개",
  "Record info": "기록 정보",
  "Chatbot record": "챗봇 기록",
  "Feedback status": "피드백 상태",
  "Service preparing": "서비스 준비 중",
  "New registration": "신규 등록",
  "Sub admin management": "서브 관리자 관리",
  "Edit": "수정",
  "Delete": "삭제",
  "Admin basic info": "관리자 기본 정보",
  "Manager": "담당자",
  "Edit admin account": "관리자 계정 수정",
  "Password": "비밀번호",
  "Password Confirm": "비밀번호 확인",
  "Password Edit Confirm": "비밀번호 수정 확인",
  "Register new admin": "신규 관리자 등록",
  "Master login": "마스터 로그인",
  "Login": "로그인",
  "Master signup": "마스터 회원가입",
  "If you have issues logging in,\ncontact mindsight@nodame.com.":
      "로그인에 문제가 있을 경우\nmindsight@nodame.com으로 문의하세요.",
  "Saved successfully": "저장 완료",
  "Save failed": "저장 실패",
  "Login Failed": "로그인 실패",
  "Login failed.": "로그인에 실패했습니다.",
  "Sign up": "회원가입",
  "Sign in": "로그인",
  "Login with Google": "구글로 로그인",
  "Sign up with Google": "구글로 회원가입",
  "Sign up with email address": "이메일로 회원가입",
  "or": "또는",
  "Don’t have an account yet?": "아직 계정이 없으신가요?",
  "Already have an account?": "이미 계정이 있으신가요?",
  "Forgot password?": "비밀번호를 잊으셨나요?",
  "Change Password": "비밀번호 변경",
  "Continue": "계속",
  "Code sent successfully.": "코드가 성공적으로 전송되었습니다.",
  "Enter a new password.": "새 비밀번호를 입력하세요.",
  "The password does not match.": "비밀번호가 일치하지 않습니다.",
  "No media file selected.": "선택된 미디어 파일이 없습니다.",
  "No thumbnail file selected.": "선택된 썸네일이 없습니다.",
  "error file extension": "잘못된 파일 확장자",
  "unsupported file type": "지원되지 않는 파일 형식",
  "Select master": "마스터 선택",
  "Master name": "마스터 이름",
  "Media playback": "미디어 재생",
  "Unable to play media.": "미디어를 재생할 수 없습니다.",
  "Invalid image URL": "잘못된 이미지 URL",
  "View image": "이미지 보기",
  "Failed to load image": "이미지를 불러올 수 없습니다",
  "Close": "닫기",
  "Verification complete": "검증 완료",
  "Crop and Rotate": "자르기 및 회전",
  "Attached File": "첨부 파일",
  "Question": "질문",
  "Answer": "답변",
  "FAQ detail": "FAQ 상세",
  "FAQ list": "FAQ 목록",
  "FAQ Board list": "FAQ 게시판 목록",
  "FAQ Board detail": "FAQ 게시판 상세",
  "FAQ Board Edit": "FAQ 게시판 수정",
  "FAQ New registration": "FAQ 신규 등록",
  "Notice list": "공지사항 목록",
  "Notice detail": "공지사항 상세",
  "Notice Board list": "공지사항 게시판 목록",
  "Notice Board detail": "공지사항 게시판 상세",
  "Notice Board Edit": "공지사항 게시판 수정",
  "Notice New registration": "공지사항 신규 등록",
  "Free Board list": "자유 게시판 목록",
  "Free Board detail": "자유 게시판 상세",
  "Free Board Edit": "자유 게시판 수정",
  "Free Board New registration": "자유 게시판 신규 등록",
  "Body": "몸체",
  "Comment List": "댓글 목록",
  "Write a Comment": "댓글 작성",
  "Inquiry board list": "문의 게시판 목록",
  "Inquiry board detail": "문의 게시판 상세",
  "Inquiry board Edit": "문의 게시판 수정",
  "Inquiry board New registration": "문의 게시판 신규 등록",
  "Response": "답변",
  "Pending": "대기 중",
  "not hovering": "호버 중 아님",
  "Login info": "로그인 정보",
  "ID": "아이디",
  "Department": "부서",
  "Permission": "권한",
  "Contact number": "연락처",
  "Recent activity": "최근 활동",
  "role": "역할",
  "Operation": "운영",
  "Product management": "상품 관리",
  "Development": "개발",
  "Select Option": "옵션 선택",
  "Change password": "비밀번호 변경",
  "Current password": "현재 비밀번호",
  "New password": "새 비밀번호",
  "Please enter some text": "텍스트를 입력하세요",
  "Created by master": "마스터 생성",
  "Exposure Status": "노출 상태",
  "Day session": "일일 세션",
  "Thumbnail file": "썸네일 파일",
  "Content": "내용",
  "Participating members": "참여 회원",
  "Completed members": "완료 회원",
  "Likes": "좋아요",
  "Exposure": "노출",
  "Note": "메모",
  "Change exposure": "노출 변경",
  "Views": "조회수",
  "Download Excel template": "엑셀 템플릿 다운로드",
  "Media File": "미디어 파일",
  "Target Language": "대상 언어",
  "Content New Registration": "콘텐츠 신규 등록",
  "Content Edit": "콘텐츠 수정",
  "Basic info": "기본 정보",
  "Register content": "콘텐츠 등록",
  "Google Analytics": "구글 애널리틱스",
  "Daily plan Complete rate": "일일 계획 완료율",
  "All View": "전체 보기",
  "Complete rate": "완료율",
  "Members accessed yesterday": "어제 접속 회원 수",
  "Number of events in the last 7 days": "지난 7일간 이벤트 수",
  "Returning members in the last 7 days": "지난 7일간 재방문 회원 수",
  "Registered users": "회원가입한 사용자",
  "Not registered": "미가입자",
  "Active members": "활성 회원",
  "Inactive members": "비활성 회원",
  "Sign-up compelete": "회원가입 완료",
  "Affiliation": "소속",
  "Conversion date": "전환일",
  "Member info Edit": "회원 정보 수정",
  "Logout": "로그아웃",
  "Cannot download image": "이미지를 다운로드할 수 없습니다",
  "Error downloading image": "이미지 다운로드 오류",
  "Failed to load video.": "비디오를 불러올 수 없습니다",
  "No aggregated data.": "집계된 데이터가 없습니다",
  "Change": "변경",
  "Breath": "호흡",
  "Theory": "이론",
  "Mindful Art": "마음챙김 아트",
  "ASMR": "ASMR",
  "Art & Music": "예술 & 음악",
  "Beginner": "초급",
  "Intermediate": "중급",
  "Advanced": "고급",
  "Satisfied": "만족함",
  "Relaxed": "편안함",
  "Calm": "차분함",
  "Sleepy": "졸림",
  "Tired": "피곤함",
  "Bored": "지루함",
  "Depressed": "우울함",
  "Sad": "슬픔",
  "Miserable": "비참함",
  "Upset": "속상함",
  "Stressed": "스트레스받음",
  "Scared": "두려움",
  "Annoyed": "짜증남",
  "Nervous": "긴장됨",
  "Angry": "화남",
  "Alarmed": "깜짝 놀람",
  "Surprised": "놀람",
  "Excited": "신남",
  "Delighted": "기쁨",
  "Happy": "행복함",
  "Just rest": "그냥 쉬기",
  "Sleep": "수면",
  "Workspace": "작업 공간",
  "Movement": "움직임",
  "Male": "남성",
  "Female": "여성",
  "Nonbinary": "논바이너리",
  "Non Exposure": "비노출",
  "You can upload video or audio files.": "비디오 또는 오디오 파일을 업로드할 수 있습니다.",

  "The media file is currently being transcoded and cannot be modified.":
      "현재 미디어 파일이 트랜스코딩 중이어서 수정할 수 없습니다.",

  "After entering tags, register by clicking '+' or pressing Enter.":
      "태그를 입력한 후 '+' 버튼을 클릭하거나 Enter 키를 눌러 등록하세요.",
  "Please enter an introduction within 150 characters.":
      "소개는 150자 이내로 입력해 주세요.",
  "Content list": "콘텐츠 목록",
  "Level": "레벨",
  "Situation": "상황",
  "Emotion": "감정",
  "Input Text": "텍스트 입력",
  "click to upload .mp4 .mp3 .wav": ".mp4 .mp3 .wav 파일을 업로드하려면 클릭하세요",
  "click to upload .jpg .jpeg .png": ".jpg .jpeg .png 파일을 업로드하려면 클릭하세요",
  "Content details": "콘텐츠 상세",
  "Join Date": "가입일",
  "First name": "이름",
  "Last name": "성",
  "Gender": "성별",
  "Year of birth": "출생 연도",
  "Date": "날짜",
  "Author": "작성자",
  "Answered": "답변 완료",
  "Comments": "댓글",
  "All Notifications": "전체 알림",
  "I receive all notifications.": "모든 알림을 받습니다.",
  "Select Notification Type": "알림 유형 선택",
  "Email": "이메일",
  "SMS": "문자",
  "Select Notification Items": "알림 항목 선택",
  "Notice": "공지",
  "Inquiries and Answers": "문의 및 답변",
  "Content Approval and Modification": "콘텐츠 승인 및 수정",
  "Settlement": "정산",
  "Please enter your display name": "표시할 이름을 입력하세요",
  "Inquiry board": "문의 게시판",
  "Help": "도움말",
  "Streaming Settlement": "스트리밍 정산",
  "Please enter the title within 100 characters.": "제목은 100자 이내로 입력해 주세요.",
  "It will be displayed in the specified language version.":
      "지정된 언어 버전으로 표시됩니다.",
  "It must be set to “exposed” in order to be shown in the service.":
      "서비스에 노출되려면 '노출' 상태로 설정해야 합니다.",
  "Processing": "처리 중",
  "Inactive master management": "비활성 마스터 관리",
  "Inactive member management": "비활성 회원 관리",

// 기존것 그냥 붙여넣기 했음
  "Company New registration": "회사 신규 등록",
  "Status": "상태",
  "Normal": "정상",
  "Content Details": "콘텐츠 상세",
  "Content New registration": "콘텐츠 신규 등록",
  "None": "안함",
  "Session info": "세션 정보",
  "Write expert feedback": "전문가 피드백 작성",
  "Search member records": "회원, 기록 내용 검색",
  "Member affiliation": "회원 소속",
  "Complete": "완료",
  "My account detail": "내 계정 상세",
  "Other settings": "기타 설정",
  "Default settings": "기본 설정",
  "Language": "언어",
  "Enter a valid email.": "유효한 이메일을 입력하세요.",
  "Password Edit": "비밀번호 수정",
  "Master New registration": "마스터 신규 등록",
  "Mindsight master page": "Mindsight 마스터페이지",
  "Business email": "비즈니스 이메일",
  "Company detail": "회사 상세",
  "Company list": "회사 목록",
  "Company info": "회사 정보",
  "Search company name": "회사 이름 검색",
  "Registration date": "등록일",
  "Registered file": "등록 파일",
  "Excel file": "엑셀 파일",
  "Bulk pre-registration": "대량 사전 신규 등록",
  "Search title": "제목 검색",
  "Change status": "상태 변경",
  "User data": "사용자 데이터",
  "Total members": "누적 참여 회원 수",
  "Rating": "별점",
  "Day session Register": "일 세션 등록",
  "File": "파일",
  "CC file": "자막 파일",
  "Challenge management": "Challenge 관리",
  "Challenge New registration": "Challenge 신규 등록",
  "Challenge Detail": "Challenge 상세",
  "Challenge Edit": "Challenge 수정",
  "Sound file": "사운드 파일",
  "Activity info": "활동 정보",
  "Completed sessions": "완료한 세션 수",
  "Total meditation time": "누적 명상 시간",
  "Consecutive meditation days": "연속 명상 일 수",
  "Total meditation days": "누적 명상 일 수",
  "Please enter a 4-digit number.": "4자리 정수를 입력해주세요.",
  "Input is too long": "Input is too long",
  "Streaming Details": "스트리밍 상세",
  "Search master name": "마스터 이름 검색",
  "Profit margin": "수익률",
  "Master details": "마스터별 상세",
  "View": "보기",
  "Download Excel": "엑셀 다운로드",
  "Select aggregation": "선택 집계",
  "Change share rate.": "쉐어율을 변경합니다.",
  "Current": "현재",
  "After change": "변경 후",
  "Settlement by play count": "작품별 플레이 횟수에 따른 정산 상세",
  "Content name": "콘텐츠명",
  "Share rate": "쉐어율",
  "Play count": "플레이 횟수",
  "View rate per content": "콘텐츠 별 시청율",
  "Settlement per content": "콘텐츠 별 정산금액",
  "Select month": "월 선택",
  "Year": "연도",
  "Month": "월",
  "not registered": "미발행",
  "inactive": "미정산",
  "registered": "발행",
  "min": "분",
  "days": "일",
  "Revenue share": "수익쉐어",
  "Master ID": "마스터 ID",
  "Previous profit margin": "이전 수익률",
  "Current profit margin": "현 수익률",
  "Monthly PG fee": "월 PG 수수료",
  "Monthly store fee": "월 스토어 수수료",
  "Monthly other fee": "월 기타 수수료",
  "Buyer name\n(Member ID)": "구매자명\n(회원 ID)",
  "Transaction datetime": "거래일시",
  "Cancellation datetime": "취소일시",
  "Membership name": "멤버쉽명",
  "Amount": "금액",
  "Approval number": "승인번호",
  "Payment agency": "결제대행사",
  "Fee": "수수료",
  "Net sales": "순매출액",
  "Other fee\n(Copyright)": "기타 수수료\n(저작권료)",
  "Total View Rate": "전체 시청 비율",
  "Total Monthly Sales": "월 전체 매출액",
  "Total Monthly Net Sales": "월 전체 순 매출액",
  "Total Monthly Play Count": "월 전체 플레이 횟수",
  "Total Monthly Payout": "월 전체 지급 금액",
  "Monthly Operating Profit": "월 영업이익",
  "Net Settlement Amount\n(Including VAT)": "실정산금액\n(부가세포함)",
  "Monthly Subscription Total Sales Detail": "월 구독 전체 매출액 상세",
  "App Payment": "앱결제",
  "Others": "기타",
  "Content management": "콘텐츠 관리",
  "Daily plan management": "Daily plan 관리",
  "Daily plan New registration": "Daily plan 신규 등록",
  "Daily plan Details": "Daily plan 상세",
  "Daily plan Edit": "Daily plan 수정",
  "Company management": "회사 관리",
  "Inactive company management": "비활성 회사 관리",
  "Dashboard": "대시보드",
  "Member management": "회원 관리",
  "Member list": "회원 목록",
  "Member details": "회원 상세",
  "Master management": "마스터 관리",
  "Master list": "마스터 목록",
  "Master info edit": "마스터 정보 수정",
  "Sales and Settlement": "매출 및 정산",
  "Master Settlement": "마스터 정산",
  "Settings": "설정",
  "Manage My Account": "내 계정 관리",
  "My Account Edit": "내 계정 수정",
  "Manage My Company": "내 회사 관리",
  "Quick View": "간략히 보기",
  "Order by Registration": "등록 순",
  "Order by Views": "조회 순",
  "Order by Likes": "좋아요 순",
  "Order by Most Participants": "참여자 많은 순",
  "Order by Least Participants": "참여자 낮은 순",
  "Order by Highest Rating": "평점 높은 순",
  "Order by Highest Completion Rate": "완료율 높은 순",
  "Order by Lowest Completion Rate": "완료율 낮은 순",
  "Basic Body": "기본 몸체",
  "Intermediate Body": "중간 몸체",
  "Advanced Body": "숙련된 몸체",
  "Natural Breathing": "자연 호흡",
  "Meditation Guide": "명상 안내",
  "Mindfulness Art": "마음챙김 예술",
  "Art with Music": "음악이 있는 예술",
  "Nature": "자연",
  "Emotion Management": "감정 관리",
  "Philosophy": "철학",
  "Self-development": "자기개발",
  "Tags": "태그",

  "Mindfulness": "마음챙김",

  "After entering tags, please register them by clicking the '+' button or pressing Enter.":
      "태그 입력 후 ‘+’ 버튼 또는 Enter로 태그를 등록 해 주십시오.",

  "Health Improvement": "건강 향상",
  "Comfortable Stretching": "편안한 스트레칭",
  "Workplace Well-being": "직장에서의 웰빙",
  "Emotion Regulation": "감정 조절",
  "Easy to Fall Asleep": "쉽게 잠들기",
  "Day": "일",
  "Unissued": "미발행",
  "Issued": "발행",
  "Unsettled": "미정산",
  "Last month": "지난 달",
  "This month": "이번 달",
  "Sales aggregation": "매출 집계",
  "Total play count": "전체 플레이 횟수",
  "Account Information": "계정 정보",
  "Photo": "사진",
  "Mobile Number": "핸드폰 번호",
  "ID Card": "신분증",
  "Country": "국가",
  "Primary Language": "제 1 언어",
  "Secondary Language": "제 2 언어",
  "Challenge, Content title": "Challenge, 콘텐츠 제목",
  "Master\nDetails": "마스터\n상세",
  "Transcoding Progress": "트랜스코딩 진행율",
  "Upload Progress": "업로드 진행율",
  "Transcoding Complete": "트랜스코딩 완료",
  "Modification successful": "수정 되었습니다",
  "Modification failed": "수정에 실패 하였습니다",
  "Using a photo of your face as a profile image whenever possible can provide more trust to members":
      "프로필로 사용되는 이미지로 되도록이면 얼굴 사진일수록 회원들에게 신뢰를 줄 수 있습니다",
  "Tax Invoice": "세금계산서",
  "Deposit Status": "지급상태",
  "Memo": "메모",
  "Payment Completed": "지급완료",
  "Help": "Help",
  "Notice": "공지사항",
  "1:1 Inquiries": "1:1 문의",
  "FAQ": "FAQ",
  "Free Board": "자유게시판",
  "Files are automatically optimized through transcoding during upload. You can save them once transcoding is complete.":
      "파일 업로드 시 자동으로 트랜스코딩을 통해 최적화됩니다. 트랜스코딩이 완료되면 저장할 수 있습니다.",
  "Transcoding is still in progress. Please wait until it completes before saving.":
      "트랜스코딩이 아직 진행 중입니다. 완료될 때까지 기다린 후 저장해 주세요.",
};
