// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzBKa_53LR-4Qw8xMKb5-f7KFdcxEsoTo',
    appId: '1:86520359521:web:1098196ff024e6c5ce5820',
    messagingSenderId: '86520359521',
    projectId: 'mindsight-admin',
    authDomain: 'master.mindsight.im',
    storageBucket: 'mindsight-admin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnCmm3cVi7Zf-2guEUdYjCbAwGmAGUUfU',
    appId: '1:86520359521:android:635acf889c96bca6ce5820',
    messagingSenderId: '86520359521',
    projectId: 'mindsight-admin',
    storageBucket: 'mindsight-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf8It9o4w3YmdH96x-aJudzpil_63p92Y',
    appId: '1:86520359521:ios:be5c04af0a096952ce5820',
    messagingSenderId: '86520359521',
    projectId: 'mindsight-admin',
    storageBucket: 'mindsight-admin.firebasestorage.app',
    iosClientId:
        '86520359521-i9nlllsqrhqk0boqh10lb3dlcea3najm.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindsightAdminPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf8It9o4w3YmdH96x-aJudzpil_63p92Y',
    appId: '1:86520359521:ios:be5c04af0a096952ce5820',
    messagingSenderId: '86520359521',
    projectId: 'mindsight-admin',
    storageBucket: 'mindsight-admin.firebasestorage.app',
    iosClientId:
        '86520359521-i9nlllsqrhqk0boqh10lb3dlcea3najm.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindsightAdminPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzBKa_53LR-4Qw8xMKb5-f7KFdcxEsoTo',
    appId: '1:86520359521:web:1098196ff024e6c5ce5820',
    messagingSenderId: '86520359521',
    projectId: 'mindsight-admin',
    authDomain: 'master.mindsight.im',
    storageBucket: 'mindsight-admin.firebasestorage.app',
  );
}
