enum ContentLanguage {
  afrikaans('아프리칸스어', 'AFRIKAANS'),
  albanian('알바니아어', 'ALBANIAN'),
  amharic('암하라어', 'AMHARIC'),
  arabic('아랍어', 'ARABIC'),
  armenian('아르메니아어', 'ARMENIAN'),
  azerbaijani('아제르바이잔어', 'AZERBAIJANI'),
  basque('바스크어', 'BASQUE'),
  belarusian('벨라루스어', 'BELARUSIAN'),
  bengali('벵골어', 'BENGALI'),
  bosnian('보스니아어', 'BOSNIAN'),
  bulgarian('불가리아어', 'BULGARIAN'),
  catalan('카탈루냐어', 'CATALAN'),
  cebuano('세부아노어', 'CEBUANO'),
  chichewa('치체와어', 'CHICHEWA'),
  chineseSimplified('중국어 간체', 'CHINESE_SIMPLIFIED'),
  chineseTraditional('중국어 번체', 'CHINESE_TRADITIONAL'),
  corsican('코르시카어', 'CORSICAN'),
  croatian('크로아티아어', 'CROATIAN'),
  czech('체코어', 'CZECH'),
  danish('덴마크어', 'DANISH'),
  dutch('네덜란드어', 'DUTCH'),
  english('영어', 'ENGLISH'),
  esperanto('에스페란토어', 'ESPERANTO'),
  estonian('에스토니아어', 'ESTONIAN'),
  filipino('필리핀어', 'FILIPINO'),
  finnish('핀란드어', 'FINNISH'),
  french('프랑스어', 'FRENCH'),
  frisian('프리지아어', 'FRISIAN'),
  galician('갈리시아어', 'GALICIAN'),
  georgian('조지아어', 'GEORGIAN'),
  german('독일어', 'GERMAN'),
  greek('그리스어', 'GREEK'),
  gujarati('구자라트어', 'GUJARATI'),
  haitianCreole('아이티 크레올어', 'HAITIAN_CREOLE'),
  hausa('하우사어', 'HAUSA'),
  hawaiian('하와이어', 'HAWAIIAN'),
  hebrew('히브리어', 'HEBREW'),
  hindi('힌디어', 'HINDI'),
  hmong('호몽어', 'HMONG'),
  hungarian('헝가리어', 'HUNGARIAN'),
  icelandic('아이슬란드어', 'ICELANDIC'),
  igbo('이그보어', 'IGBO'),
  indonesian('인도네시아어', 'INDONESIAN'),
  irish('아일랜드어', 'IRISH'),
  italian('이탈리아어', 'ITALIAN'),
  japanese('일본어', 'JAPANESE'),
  javanese('자바어', 'JAVANESE'),
  kannada('칸나다어', 'KANNADA'),
  kazakh('카자흐어', 'KAZAKH'),
  khmer('크메르어', 'KHMER'),
  korean('한국어', 'KOREAN'),
  kurdish('쿠르드어', 'KURDISH'),
  kyrgyz('키르기스어', 'KYRGYZ'),
  lao('라오어', 'LAO'),
  latin('라틴어', 'LATIN'),
  latvian('라트비아어', 'LATVIAN'),
  lithuanian('리투아니아어', 'LITHUANIAN'),
  luxembourgish('룩셈부르크어', 'LUXEMBOURGISH'),
  macedonian('마케도니아어', 'MACEDONIAN'),
  malagasy('말라가시어', 'MALAGASY'),
  malay('말레이어', 'MALAY'),
  malayalam('말라얄람어', 'MALAYALAM'),
  maltese('몰타어', 'MALTESE'),
  maori('마오리어', 'MAORI'),
  marathi('마라티어', 'MARATHI'),
  mongolian('몽골어', 'MONGOLIAN'),
  myanmar('버마어', 'MYANMAR'),
  nepali('네팔어', 'NEPALI'),
  norwegian('노르웨이어', 'NORWEGIAN'),
  odia('오디아어', 'ODIA'),
  pashto('파슈토어', 'PASHTO'),
  persian('페르시아어', 'PERSIAN'),
  polish('폴란드어', 'POLISH'),
  portuguese('포르투갈어', 'PORTUGUESE'),
  punjabi('펀자브어', 'PUNJABI'),
  romanian('루마니아어', 'ROMANIAN'),
  russian('러시아어', 'RUSSIAN'),
  samoan('사모아어', 'SAMOAN'),
  scotsGaelic('스코틀랜드 게일어', 'SCOTS_GAELIC'),
  serbian('세르비아어', 'SERBIAN'),
  sesotho('세소토어', 'SESOTHO'),
  shona('쇼나어', 'SHONA'),
  sindhi('신디어', 'SINDHI'),
  sinhala('싱할라어', 'SINHALA'),
  slovak('슬로바키아어', 'SLOVAK'),
  slovenian('슬로베니아어', 'SLOVENIAN'),
  somali('소말리어', 'SOMALI'),
  spanish('스페인어', 'SPANISH'),
  sundanese('순다어', 'SUNDANESE'),
  swahili('스와힐리어', 'SWAHILI'),
  swedish('스웨덴어', 'SWEDISH'),
  tajik('타지크어', 'TAJIK'),
  tamil('타밀어', 'TAMIL'),
  telugu('텔루구어', 'TELUGU'),
  thai('태국어', 'THAI'),
  turkish('터키어', 'TURKISH'),
  ukrainian('우크라이나어', 'UKRAINIAN'),
  urdu('우르두어', 'URDU'),
  uzbek('우즈벡어', 'UZBEK'),
  vietnamese('베트남어', 'VIETNAMESE'),
  welsh('웨일스어', 'WELSH'),
  xhosa('코사어', 'XHOSA'),
  yiddish('이디시어', 'YIDDISH'),
  yoruba('요루바어', 'YORUBA'),
  zulu('줄루어', 'ZULU');

  final String _displayName;
  final String _keywordName;

  const ContentLanguage(this._displayName, this._keywordName);

  String get displayName => _displayName;
  String get keywordName => _keywordName;

  static ContentLanguage fromKeyword(String value) {
    return ContentLanguage.values.firstWhere(
      (v) => v.keywordName == value,
      orElse: () => ContentLanguage.english,
    );
  }
}
